In [1]:
import os
import numpy as np
import pandas as pd
import gc

In [2]:
sub0 = pd.read_csv('C:/Users/Michael/Github/sample_submission.csv').sort_values('customer_id').reset_index(drop=True)

In [3]:
sub1 = pd.read_csv('submission_04_30_2022.csv').sort_values('customer_id').reset_index(drop=True)

In [4]:
sub2= pd.read_csv('submission_other_sub.csv').sort_values('customer_id').reset_index(drop=True)

In [5]:
sub0.columns = ['customer_id', 'prediction0']
sub0['prediction1'] = sub1['prediction']
sub0['prediction2'] = sub2['prediction']
sub0.drop('prediction0',axis=1,inplace=True)
sub0.head()

,customer_id,prediction1,prediction2
0,00000dbacae5abe5e23885899a1fa44253a17956c6d1c3...,0568601043 0568601006 0924243001 0924243002 09...,0568601043 0568601006 0568601006 0568597006 04...
1,0000423b00ade91418cceaf3b26c6af3dd342b51fd051e...,0826211002 0706016001 0924243001 0924243002 09...,0826211002 0800436010 0739590027 0706016001 06...
2,000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...,0794321007 0805000001 0924243001 0924243002 09...,0794321007 0852643001 0852643003 0858883002 07...
3,00005ca1c9ed5f5146b52ac8639a40ca9d57aeff4d1bd2...,0742079001 0732413001 0730683001 0372860001 09...,0448509014 0573085028 0751471001 0706016001 06...
4,00006413d8573cd20ed7128e53b7b13819fe5cfc2d801f...,0896152002 0730683050 0927530004 0791587015 08...,0730683050 0791587015 0896152002 0818320001 09...

In [6]:
del sub1, sub2
gc.collect()

0

In [7]:
sub0

,customer_id,prediction1,prediction2
0,00000dbacae5abe5e23885899a1fa44253a17956c6d1c3...,0568601043 0568601006 0924243001 0924243002 09...,0568601043 0568601006 0568601006 0568597006 04...
1,0000423b00ade91418cceaf3b26c6af3dd342b51fd051e...,0826211002 0706016001 0924243001 0924243002 09...,0826211002 0800436010 0739590027 0706016001 06...
2,000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...,0794321007 0805000001 0924243001 0924243002 09...,0794321007 0852643001 0852643003 0858883002 07...
3,00005ca1c9ed5f5146b52ac8639a40ca9d57aeff4d1bd2...,0742079001 0732413001 0730683001 0372860001 09...,0448509014 0573085028 0751471001 0706016001 06...
4,00006413d8573cd20ed7128e53b7b13819fe5cfc2d801f...,0896152002 0730683050 0927530004 0791587015 08...,0730683050 0791587015 0896152002 0818320001 09...
...,...,...,...
1371975,ffffbbf78b6eaac697a8a5dfbfd2bfa8113ee5b403e474...,0713997002 0720125039 0740922009 0791587007 08...,0804992033 0720125039 0713997002 0557599022 07...
1371976,ffffcd5046a6143d29a04fb8c424ce494a76e5cdf4fab5...,0762846031 0762846008 0924243001 0924243002 09...,0818754002 0762846031 0759871030 0624486088 08...
1371977,ffffcf35913a0bee60e8741cb2b4e78b8a98ee5ff2e6a1...,0762846027 0689365050 0884081001 0794819001 07...,0884081001 0762846027 0794819001 0689365050 06...
1371978,ffffd7744cebcf3aca44ae7049d2a94b87074c3d4ffe38...,0882810001 0464297007 0924243001 0924243002 09...,0882810001 0714790020 0464297007 0448509014 04...
1371979,ffffd9ac14e89946416d80e791d064701994755c3ab686...,0806050001 0706016002 0924243001 0924243002 09...,0806050001 0706016002 0448509014 0573085028 07...

In [8]:
def cust_blend(dt, W = [1,1,1,1,1,1,1,1]):
    #Global ensemble weights
    #W = [1.15,0.95,0.85]

    #Create a list of all model predictions
    REC = []

    # Second Try
#     REC.append(dt['prediction0'].split())
    REC.append(dt['prediction1'].split())
    REC.append(dt['prediction2'].split())

    #Create a dictionary of items recommended.
    #Assign a weight according the order of appearance and multiply by global weights
    res = {}
    for M in range(len(REC)):
        for n, v in enumerate(REC[M]):
            if v in res:
                res[v] += (W[M]/(n+1))
            else:
                res[v] = (W[M]/(n+1))

    # Sort dictionary by item weights
    res = list(dict(sorted(res.items(), key=lambda item: -item[1])).keys())

    # Return the top 12 items only
    return ' '.join(res[:12])

In [9]:
# sub0['prediction'] = sub0.apply(cust_blend, W = [1.05, 0.75, 1.00, 0.95, 0.65, 0.90, 0.80, 0.55], axis=1)
sub0['prediction'] = sub0.apply(cust_blend, W = [1.05, 0.78, 0.86, 0.85, 0.68, 0.64, 0.70, 0.24], axis=1)
# sub0['prediction'] = sub0.apply(cust_blend, W = [1.05, 0.78, 0.86, 0.85, 0.68, 0.64, 0.70, 0.24, 1.01], axis=1)

sub0.head()

,customer_id,prediction1,prediction2,prediction
0,00000dbacae5abe5e23885899a1fa44253a17956c6d1c3...,0568601043 0568601006 0924243001 0924243002 09...,0568601043 0568601006 0568601006 0568597006 04...,0568601043 0568601006 0924243001 0924243002 04...
1,0000423b00ade91418cceaf3b26c6af3dd342b51fd051e...,0826211002 0706016001 0924243001 0924243002 09...,0826211002 0800436010 0739590027 0706016001 06...,0826211002 0706016001 0800436010 0924243001 09...
2,000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...,0794321007 0805000001 0924243001 0924243002 09...,0794321007 0852643001 0852643003 0858883002 07...,0794321007 0805000001 0852643001 0924243001 09...
3,00005ca1c9ed5f5146b52ac8639a40ca9d57aeff4d1bd2...,0742079001 0732413001 0730683001 0372860001 09...,0448509014 0573085028 0751471001 0706016001 06...,0742079001 0448509014 0732413001 0573085028 07...
4,00006413d8573cd20ed7128e53b7b13819fe5cfc2d801f...,0896152002 0730683050 0927530004 0791587015 08...,0730683050 0791587015 0896152002 0818320001 09...,0896152002 0730683050 0791587015 0927530004 08...

In [11]:
# del sub0['prediction0']
# del sub0['prediction1']
# del sub0['prediction2']
# gc.collect()

In [15]:
sub1 = pd.read_csv('C:/Users/Michael/Github/sample_submission.csv').sort_values('customer_id').reset_index(drop=True)
#main
sub1['prediction'] = sub0['prediction'].astype(str)
# sub0.columns = ['customer_id', 'prediction0']

sub2 = pd.read_csv('submission_04_30_2022.csv').sort_values('customer_id').reset_index(drop=True)
sub1['prediction1'] = sub2['prediction']

sub3 = pd.read_csv('submission_other_sub.csv').sort_values('customer_id').reset_index(drop=True)
sub1['prediction2'] = sub3['prediction']

gc.collect()

488

In [16]:
sub1

,customer_id,prediction,prediction1,prediction2
0,00000dbacae5abe5e23885899a1fa44253a17956c6d1c3...,0568601043 0568601006 0924243001 0924243002 04...,0568601043 0568601006 0924243001 0924243002 09...,0568601043 0568601006 0568601006 0568597006 04...
1,0000423b00ade91418cceaf3b26c6af3dd342b51fd051e...,0826211002 0706016001 0800436010 0924243001 09...,0826211002 0706016001 0924243001 0924243002 09...,0826211002 0800436010 0739590027 0706016001 06...
2,000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...,0794321007 0805000001 0852643001 0924243001 09...,0794321007 0805000001 0924243001 0924243002 09...,0794321007 0852643001 0852643003 0858883002 07...
3,00005ca1c9ed5f5146b52ac8639a40ca9d57aeff4d1bd2...,0742079001 0448509014 0732413001 0573085028 07...,0742079001 0732413001 0730683001 0372860001 09...,0448509014 0573085028 0751471001 0706016001 06...
4,00006413d8573cd20ed7128e53b7b13819fe5cfc2d801f...,0896152002 0730683050 0791587015 0927530004 08...,0896152002 0730683050 0927530004 0791587015 08...,0730683050 0791587015 0896152002 0818320001 09...
...,...,...,...,...
1371975,ffffbbf78b6eaac697a8a5dfbfd2bfa8113ee5b403e474...,0713997002 0804992033 0720125039 0740922009 07...,0713997002 0720125039 0740922009 0791587007 08...,0804992033 0720125039 0713997002 0557599022 07...
1371976,ffffcd5046a6143d29a04fb8c424ce494a76e5cdf4fab5...,0762846031 0818754002 0762846008 0924243001 09...,0762846031 0762846008 0924243001 0924243002 09...,0818754002 0762846031 0759871030 0624486088 08...
1371977,ffffcf35913a0bee60e8741cb2b4e78b8a98ee5ff2e6a1...,0762846027 0884081001 0689365050 0794819001 07...,0762846027 0689365050 0884081001 0794819001 07...,0884081001 0762846027 0794819001 0689365050 06...
1371978,ffffd7744cebcf3aca44ae7049d2a94b87074c3d4ffe38...,0882810001 0464297007 0448509014 0714790020 09...,0882810001 0464297007 0924243001 0924243002 09...,0882810001 0714790020 0464297007 0448509014 04...
1371979,ffffd9ac14e89946416d80e791d064701994755c3ab686...,0806050001 0706016002 0924243001 0448509014 07...,0806050001 0706016002 0924243001 0924243002 09...,0806050001 0706016002 0448509014 0573085028 07...

In [19]:
def cust_blend(dt, W = [1,1,1,1,1]):
    #Global ensemble weights
    #W = [1.15,0.95,0.85]

    #Create a list of all model predictions
    REC = []

    # Second Try
    REC.append(dt['prediction'].split())
    REC.append(dt['prediction1'].split())
    REC.append(dt['prediction2'].split())

    #Create a dictionary of items recommended.
    #Assign a weight according the order of appearance and multiply by global weights
    res = {}
    for M in range(len(REC)):
        for n, v in enumerate(REC[M]):
            if v in res:
                res[v] += (W[M]/(n+1))
            else:
                res[v] = (W[M]/(n+1))

    # Sort dictionary by item weights
    res = list(dict(sorted(res.items(), key=lambda item: -item[1])).keys())

    # Return the top 12 items only
    return ' '.join(res[:12])

In [21]:
sub0['prediction_final'] = sub0.apply(cust_blend, W = [1.20, 0.85, 0.60], axis=1)

In [23]:
del sub0['prediction1']
del sub0['prediction2']
del sub0['prediction']

In [25]:
sub0.columns = ['customer_id','prediction']

In [27]:
sub0.to_csv('submission_Essemble_Method.csv', index=False)

In [26]:
sub0

,customer_id,prediction
0,00000dbacae5abe5e23885899a1fa44253a17956c6d1c3...,0568601043 0568601006 0924243001 0924243002 04...
1,0000423b00ade91418cceaf3b26c6af3dd342b51fd051e...,0826211002 0706016001 0800436010 0924243001 09...
2,000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...,0794321007 0805000001 0852643001 0924243001 09...
3,00005ca1c9ed5f5146b52ac8639a40ca9d57aeff4d1bd2...,0742079001 0448509014 0732413001 0573085028 07...
4,00006413d8573cd20ed7128e53b7b13819fe5cfc2d801f...,0896152002 0730683050 0791587015 0927530004 08...
...,...,...
1371975,ffffbbf78b6eaac697a8a5dfbfd2bfa8113ee5b403e474...,0713997002 0804992033 0720125039 0740922009 07...
1371976,ffffcd5046a6143d29a04fb8c424ce494a76e5cdf4fab5...,0762846031 0818754002 0762846008 0924243001 09...
1371977,ffffcf35913a0bee60e8741cb2b4e78b8a98ee5ff2e6a1...,0762846027 0884081001 0689365050 0794819001 07...
1371978,ffffd7744cebcf3aca44ae7049d2a94b87074c3d4ffe38...,0882810001 0464297007 0448509014 0714790020 09...
1371979,ffffd9ac14e89946416d80e791d064701994755c3ab686...,0806050001 0706016002 0924243001 0448509014 07...

In [37]:
gc.collect()

706